from . import recruitment_base
from . import ir_attachment
from . import hr_department
from . import res_users
from . import recruitment_request
from . import recruitment_schedule_interview_wizard
from . import recruitment_candidate
from . import recruitment_stage
from . import recruitment_interview_config
from . import recruitment_interview_round
from . import recruitment_reject_wizard
from . import recruitment_add_candidate_wizard
from . import recruitment_share_candidates_wizard
from . import recruitment_send_manager_wizard
from . import recruitment_send_invitation_wizard
from . import recruitment_final_selection_wizard
from . import recruitment_set_to_new_wizard
from . import recruitment_request_reset_wizard
from . import recruitment_request_reject_wizard
from . import recruitment_candidate_send_hm_wizard
from . import recruitment_it_onboarding
from . import recruitment_it_onboarding_send_wizard
from . import recruitment_final_approval
from . import recruitment_reschedule_reason_wizard
from . import recruitment_dashboard
