{
    'name': 'Project Extended RK',
    'version': '1.5',
    'depends': ['project', 'sale', 'sale_timesheet', 'account', 'hr_timesheet', 'crm_extended_rk'],
    'author': 'Rohit',
    'category': 'Project',
    'data': [
        'security/ir.model.access.csv',
        'security/res_users_view.xml',
        'views/project_groups.xml',
        'views/project_project_views.xml',
        'views/project_team_views.xml',
        'views/project_task_views.xml',
        'wizards/sale_order_advance_wizard_view.xml',
        'data/email_template.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
}
