{
    'name': 'Project Extended RK',
    'version': '1.11',
    'depends': ['project', 'sale', 'sale_timesheet', 'account', 'hr_timesheet', 'crm_extended_rk', 'aml_automation_extended_rk'],
    'author': 'Rohit',
    'category': 'Project',
    'data': [
        'security/ir.model.access.csv',
        'security/deadline_alert_groups.xml',
        'security/res_users_view.xml',
        'views/project_groups.xml',
        'views/project_project_views.xml',
        'views/project_team_views.xml',
        'views/project_task_views.xml',
        'views/deadline_alert_views.xml',
        'views/engagement_tracking_views.xml',
        'views/project_invoice_alert_views.xml',
        'wizards/sale_order_advance_wizard_view.xml',
        'wizards/deadline_alert_test_wizard_view.xml',
        'data/email_template.xml',
        'data/deadline_alert_cron.xml',
        'data/project_hold_tag.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
}
