{
    'name': 'Recruitment GK',
    'version': '18.0.1.20.0',
    'category': 'Human Resources/Recruitment',
    'summary': 'Complete Recruitment Workflow — Requests, Candidates & Interview Pipeline',
    'author': 'KGRN',
    'icon': '/recruitment_gk/static/description/icon.png',
    'depends': ['base', 'mail', 'hr'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/recruitment_sequence.xml',
        'data/recruitment_stage_data.xml',
        'data/mail_templates.xml',
        'views/recruitment_request_views.xml',
        'views/recruitment_candidate_views.xml',
        'views/recruitment_add_candidate_wizard_views.xml',
        'views/recruitment_share_candidates_wizard_views.xml',
        'views/recruitment_send_manager_wizard_views.xml',
        'views/recruitment_schedule_interview_wizard_views.xml',
        'views/recruitment_send_invitation_wizard_views.xml',
        'views/recruitment_final_selection_wizard_views.xml',
        'views/recruitment_set_to_new_wizard_views.xml',
        'views/recruitment_request_reset_wizard_views.xml',
        'views/recruitment_request_reject_wizard_views.xml',
        'views/recruitment_reschedule_reason_wizard_views.xml',
        'views/recruitment_candidate_send_hm_wizard_views.xml',
        'views/recruitment_pipeline_views.xml',
        'views/recruitment_interview_round_views.xml',
        'views/recruitment_config_views.xml',
        'views/recruitment_department_views.xml',
        'views/recruitment_report_views.xml',
        'views/recruitment_final_approval_views.xml',
        'views/recruitment_it_onboarding_views.xml',
        'views/recruitment_it_onboarding_send_wizard_views.xml',
        'views/recruitment_dashboard_views.xml',
        'views/res_users_views.xml',
        'views/menu.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'recruitment_gk/static/src/css/recruitment_gk.css',
            'recruitment_gk/static/src/js/priority_no_autosave.js',
            'recruitment_gk/static/src/js/cv_attachment_download.js',
            'recruitment_gk/static/src/js/float_time_ampm.js',
            'recruitment_gk/static/src/xml/cv_attachment_download.xml',
            'recruitment_gk/static/src/xml/float_time_ampm.xml',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
