{
    'name': 'MIS Dashboard',
    'version': '18.0.3.5.1',
    'summary': 'Project-wise MIS Dashboard & Outstanding Report',
    'category': 'Project',
    'author': 'KGRN',
    'depends': [
        'base',
        'mail',
        'project',
        'sale',
        'sale_project',
        'account',
        'hr',
        'hr_timesheet',
        'hr_contract',
        'project_extended_rk',
    ],
    'data': [
        'security/groups.xml',
        'security/ir_rules.xml',
        'security/ir.model.access.csv',
        'views/mis_res_users_view.xml',
        'views/mis_revenue_role_views.xml',
        'views/mis_employee_views.xml',
        'views/mis_project_wise_views.xml',
        'views/mis_outstanding_views.xml',
        'views/mis_project_revenue_views.xml',
        'views/mis_performance_views.xml',
        'views/mis_performance_report_log_views.xml',
        'report/mis_warning_notice_report.xml',
        'views/mis_warning_notice_views.xml',
        'data/mis_warning_notice_data.xml',
        'views/mis_menus.xml',
        'data/mis_performance_scorecard_data.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'mis_report_kgrn/static/src/scss/mis_report_view.scss',
            'mis_report_kgrn/static/src/js/mis_report_view.js',
            'mis_report_kgrn/static/src/xml/mis_report_view.xml',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
