{
    'name': 'Client Helpdesk GK',
    'version': '18.0.2.52.0',
    'category': 'Services/Helpdesk',
    'summary': 'Public client submission portal with helpdesk ticket workflow and reporting',
    'author': 'KGRN',
    'icon': '/client_helpdesk_portal/static/description/icon.png',
    'depends': ['base', 'mail', 'website', 'contacts', 'hr'],
    'data': [
        'security/security.xml',
        'security/record_rules.xml',
        'security/ir.model.access.csv',
        'data/helpdesk_sequence.xml',
        'data/helpdesk_stages.xml',
        'data/helpdesk_config_defaults.xml',
        'data/helpdesk_cron.xml',
        'views/helpdesk_stage_views.xml',
        'views/helpdesk_portal_user_views.xml',
        'views/helpdesk_notification_log_views.xml',
        'views/helpdesk_ticket_views.xml',
        'views/helpdesk_close_wizard_views.xml',
        'views/res_config_settings_views.xml',
        'views/helpdesk_report_views.xml',
        'views/portal_templates.xml',
        'views/portal_reopen_templates.xml',
        'views/portal_track_templates.xml',
        'views/portal_dashboard_templates.xml',
        'views/menu.xml',
    ],
    'demo': [
        'data/demo_data.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'client_helpdesk_portal/static/src/css/helpdesk_portal.css',
            'client_helpdesk_portal/static/src/js/helpdesk_portal.js',
        ],
        'web.assets_backend': [
            'client_helpdesk_portal/static/src/js/attachment_preview_field.js',
            'client_helpdesk_portal/static/src/xml/attachment_preview_field.xml',
            'client_helpdesk_portal/static/src/scss/attachment_preview.scss',
            'client_helpdesk_portal/static/src/scss/helpdesk_kanban.scss',
            'client_helpdesk_portal/static/src/scss/helpdesk_form.scss',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'post_init_hook': 'post_init_hook',
}
