{
    'name': 'Referral',
    'version': '18.0.2.0.8',
    'category': 'Sales/CRM',
    'summary': 'Referral portal integration with tier-based commission tracking',
    'author': 'KGRN Chartered Accountants',
    'website': 'https://kgrnaudit.com',
    'depends': ['crm', 'mail', 'crm_iap_enrich', 'sale', 'sale_order_approval', 'account'],
    'data': [
        'security/referral_groups.xml',
        'security/ir.model.access.csv',
        'security/referral_rules.xml',
        'data/crm_stage_data.xml',
        'data/crm_tag_data.xml',
        'data/mail_templates.xml',
        'views/referral_referrer_views.xml',
        'views/crm_lead_views.xml',
        'views/referral_commission_views.xml',
        'views/referral_payment_wizard_views.xml',
        'views/referral_dashboard_views.xml',
        'views/referral_settings_views.xml',
        'views/referral_menu.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
