from . import ir_attachment
from . import it_folder_add_document
from . import it_category
from . import it_tag
from . import it_folder
from . import it_document
from . import it_document_line
from . import it_document_version
from . import it_dashboard
