{
    'name': 'Helpdesk RK',
    'version': '1.0',
    'category': 'Services',
    'summary': 'Custom Helpdesk module with email integration',
    'author': 'YourName',
    'depends': ['mail', 'bus'],
    'data': [
        'security/helpdesk_security.xml',
        'security/ir.model.access.csv',
        'data/helpdesk_data.xml',
        'data/ir_sequence.xml',
        'data/helpdesk_cron.xml',
        'views/helpdesk_views.xml',
        'views/helpdesk_menu.xml',
        'views/helpdesk_reject_wizard_views.xml',
        'views/helpdesk_deadline_wizard_views.xml',
    ],
    'images': ['static/description/icon.png'],
    'assets': {
        'web.assets_backend': [
            'helpdesk_rk/static/src/utils/silence_destroyed_error.js',
            'helpdesk_rk/static/src/chat/ticket_chat.js',
            'helpdesk_rk/static/src/chat/ticket_chat.xml',
            'helpdesk_rk/static/src/chat/ticket_chat.scss',
            'helpdesk_rk/static/src/chatter/chatter_patch.xml',
            'helpdesk_rk/static/src/chatter/chatter_simplify.scss',
            'helpdesk_rk/static/src/kanban/helpdesk_kanban.scss',
            'helpdesk_rk/static/src/kanban/helpdesk_ticket_bell_field.js',
            'helpdesk_rk/static/src/kanban/helpdesk_ticket_bell_field.xml',
            'helpdesk_rk/static/src/kanban/helpdesk_ticket_kanban_controller.js',
            'helpdesk_rk/static/src/kanban/helpdesk_ticket_kanban_all.js',
            'helpdesk_rk/static/src/list/helpdesk_ticket_list_controller.js',
            'helpdesk_rk/static/src/attachment_preview/attachment_preview.js',
            'helpdesk_rk/static/src/attachment_preview/attachment_preview.xml',
            'helpdesk_rk/static/src/attachment_preview/attachment_preview.scss',
            'helpdesk_rk/static/src/form/helpdesk_form.scss',
            'helpdesk_rk/static/src/form/helpdesk_form_controller.js',
            'helpdesk_rk/static/src/form/helpdesk_favorite_field.js',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
